os: linux

services:
  - docker

env:
  global:
    - JANUS_VERSION_COMMIT="19c5ee80972a9c2aea8f8611df4b35eef4e9598e"
    - USER_ID=1000
    - GID=1000
    - DOCKER_USER="techteamer"

before_install:
  - docker pull registry.access.redhat.com/ubi9/ubi-minimal

install:
  # Fázis 1: JANUS COMPILE STAGE
	- docker run -d --privileged --name janus_compile -v $(pwd):/workspace registry.access.redhat.com/ubi9/ubi-minimal sleep infinity
  - docker exec janus_compile bash -c "microdnf -y update && microdnf -y install dnf wget tar gcc-c++ make automake cmake libtool pkgconf"
  - docker exec janus_compile cp /workspace/test/install/dnf/dnf.conf /etc/dnf/
  - docker exec janus_compile cp /workspace/test/install/yum/CentOS.repo /etc/yum.repos.d/
  - docker exec janus_compile cp /workspace/test/install/yum/RPM-GPG-KEY-centosofficial /etc/pki/rpm-gpg/
  - docker exec janus_compile bash -c "rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm"
  - docker exec janus_compile bash -c "rpm -Uvh https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-9.noarch.rpm"
  - docker exec janus_compile bash -c "microdnf -y clean all && rpm -e --nodeps openssl-fips-provider && microdnf -y update"
  - docker exec janus_compile bash -c "microdnf -y install ffmpeg-devel libogg-devel jansson-devel openssl-devel glib2-devel libconfig-devel gengetopt gnutls-devel gtk-doc zlib-devel"

  # Libnice telepítése
  - docker exec janus_compile bash -c "cd /workspace && wget -q -O libnice-0.1.17.tar.gz https://github.com/libnice/libnice/archive/refs/tags/0.1.17.tar.gz && tar xzf libnice-0.1.17.tar.gz && rm libnice-0.1.17.tar.gz && cd libnice-0.1.17 && ./autogen.sh && ./configure && make && make install"

  # Libsrtp telepítése
  - docker exec janus_compile bash -c "cd /workspace && wget -q https://github.com/cisco/libsrtp/archive/v2.5.0.tar.gz && tar xzf v2.5.0.tar.gz && rm v2.5.0.tar.gz && cd libsrtp-2.5.0 && ./configure --prefix=/usr/local --enable-openssl && make shared_library && make install"

  # Libwebsockets telepítése
  - docker exec janus_compile bash -c "cd /workspace && wget -q https://github.com/warmcat/libwebsockets/archive/v4.3.2.tar.gz && tar xzf v4.3.2.tar.gz && rm v4.3.2.tar.gz && cd libwebsockets-4.3.2 && mkdir build && cd build && cmake -DLWS_MAX_SMP=1 -DLWS_WITHOUT_TEST_SERVER=1 -DLWS_WITHOUT_TESTAPPS=1 -DLWS_WITHOUT_CLIENT=1 -DCMAKE_INSTALL_PREFIX:PATH=/usr/local -DCMAKE_C_FLAGS='-fpic' .. && make && make install"

  # Janus Gateway fordítása és telepítése
  - docker exec janus_compile bash -c "cd /workspace/janus-gateway && rm -rf .git .github .gitignore .gitattributes"
  - docker exec janus_compile bash -c "cd /workspace/janus-gateway && sh autogen.sh && ./configure --enable-post-processing --disable-data-channels --disable-all-plugins --enable-plugin-echotest --enable-plugin-videoroom --disable-all-transports --enable-websockets && make && make install"

script:
  # Fázis 2: BUILD STAGE
  - docker run -d --name build_janus -v $(pwd):/workspace registry.access.redhat.com/ubi9/ubi-minimal sleep infinity
  - docker exec build_janus cp /workspace/test/install/install-os.sh /install/install-os.sh
  - docker exec build_janus cp /workspace/test/install/install-supervisor.sh /install/install-supervisor.sh
  - docker exec build_janus cp /workspace/test/install/install-janus-runtime-env.sh /install/install-janus-runtime-env.sh
  - docker exec build_janus sh -x /install/install-os.sh
  - docker exec build_janus bash -c "groupadd -g $GID $DOCKER_USER && useradd -m -u $USER_ID -g $DOCKER_USER $DOCKER_USER"
  - docker exec build_janus sh -x /install/install-supervisor.sh $DOCKER_USER
  - docker exec build_janus sh -x /install/install-janus-runtime-env.sh
  - docker exec build_janus bash -c "[ ! -e /usr/local/lib/libsrtp2.so ] && ln -s /usr/local/lib/libsrtp2.so.1 /usr/local/lib/libsrtp2.so || echo 'Link already exists'"
  - docker exec build_janus bash -c "[ ! -e /usr/local/lib/libnice.so.10 ] && ln -s /usr/local/lib/libnice.so.10.10.0 /usr/local/lib/libnice.so.10 || echo 'Link already exists'"
  - docker exec build_janus bash -c "[ ! -e /usr/local/lib/libnice.so ] && ln -s /usr/local/lib/libnice.so.10.10.0 /usr/local/lib/libnice.so || echo 'Link already exists'"
  - docker exec build_janus bash -c "[ ! -e /usr/local/lib/libwebsockets.so ] && ln -s /usr/local/lib/libwebsockets.so.19 /usr/local/lib/libwebsockets.so || echo 'Link already exists'"

  # Tesztelés futtatása
  - docker exec build_janus bash -c "cd /workspace/test && ./check_janus.sh"

after_script:
  - docker stop janus_compile
  - docker stop build_janus
